### PR TITLE
Allow use of star in cors whitelist

### PR DESCRIPTION
**Pull request by markelog**
Not sure who to test this, any ideas?

### CODE REVIEW

**Comment by Avaq** [comment]
The star is dangerous no? As it defeats the point of using white-list based security. I'm afraid this will encourage developers to simply put a `*` there and forget about it, causing applications to be deployed without any kind of cross-origin protection.

**Comment by Beanow** [comment]
A subdomain wildcard may be an addition worth considering though.
But agreed that just `*` is a terrible idea. Should you want this for quick prototyping, it's better to implement this locally, not in the skeleton.

**Comment by markelog** [comment]
> The star is dangerous no?

Very much so, yeah, but that's only for the development/test environments, if you like, we can explicitly set `cors` property in production config

**Comment by Avaq** [comment]
What do we think of allowing all cross-origin requests by default if the app is running with `NODE_ENV` set to `development`?

I essentially suggest hard-coding the `*` over giving developers a dangerous feature.

This means you'll have no CORS issues when running with `npm run dev`. The app crashes during bootstrap when started without `NODE_ENV` set, so that should be safe.

**Comment by markelog** [comment]
I think its a bit overcomplicated, it makes configuration unpredictable i.e. you can define `cors` property in development and production, but it will take effect only in production?

No worries though, will be doing this in the apps, wouldn't want to you do merge something you are unsure of :)

**Pull request closed without merging**
