### PR TITLE
Simplify 'lint:fix' execution

### PR DESCRIPTION
**Pull request by markelog**
That way, you don't need to duplicate folder list in two places

### CODE REVIEW

**Comment by markelog** [comment]
Personally, I would just remove `lint:fix` command, but it seems proposed use of npm feature is still not that well known?

**Comment by Avaq** [comment]
> Personally, I would just remove lint:fix command

In favour of `npm run lint -- --fix`?

> it seems proposed use of npm feature is still not that well known

The feature described above?

**Comment by Beanow** [comment]
> Personally, I would just remove lint:fix command
In practice I run both the linting and fixing from my IDE integration.
The normal lint is useful as a CI test though.

**Comment by markelog** [comment]
@Avaq

> The feature described above?

Yep

@Beanow 

> In practice I run both the linting and fixing from my IDE integration.
The normal lint is useful as a CI test though.

You would still can do those things

**Comment by Avaq** [comment]
I think it does no harm to leave `lint:fix` in; I prefer typing less. But the changes made by this commit are absolutely reasonable.

**Pull request merged**
